name: Run Python Script and Update README

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Substitua com a versão do Python que você está utilizando
      
      - name: Run Python script
        run: python update_readme.py
      
      - name: Commit and push changes
        run: |
          git add .
          git diff
          git config --global user.email "github-actions-bot@sans-script.github.io"
          git config --global user.name "sans-script/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
