name: Waka Badges 

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Readme with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: false
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_TIMEZONE: false
          SHOW_OS: false
          SHOW_LANGUAGE: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_UPDATED_DATE: false
          SECTION_NAME: badges
